apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-read
roleRef:
  kind: ClusterRole
  name: fluent-bit-read
  apiGroup: ""
subjects:
- kind: ServiceAccount
  name: fluent-bit
  namespace: logging
